
import type { Metadata } from 'next';
import { MantineProvider, ColorSchemeScript } from '@mantine/core';

import Header from '@/components/header/header';
import Footer from '@/components/footer/footer';
import Slider from '@/components/slider/slider';
import Background from '@/components/background/background';
import ContextWrapper from '@/components/context-wrapper/context-wrapper';

import '@mantine/core/styles.css';
import styles from './layout.module.scss';
import './globals.scss';

export const metadata: Metadata = {
  title: 'Ivan Kotov',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={styles.body}>
        <MantineProvider>
          <ContextWrapper>
          <Background />
          <Header />

          <main className={styles.main}>
            <Slider>
              { children }
            </Slider>
          </main>

          <Footer />
          </ContextWrapper>
        </MantineProvider>
      </body>
    </html>
  )
}